version: '3.8'

services:
  financeiro-api:
    image: financeiro-api:${TAG:-latest}
    build:
        context: .
        dockerfile: Dockerfile
    container_name: financeiro-api
    ports:
        - "5000:8080"
    environment:
       - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    networks:
        - financeiro-network

networks:
    financeiro-network:
        driver: bridge